from datetime import datetime
from log_analyzer import analyze_logs


def generate_report(target=None, scan_results=None):

    print("\n=== PySec Report Generator ===")

    # ==========================================
    # RUN LOG ANALYSIS
    # ==========================================

    results = analyze_logs()

    # Handle missing log file
    if results is None:
        print("[ERROR] Report could not be generated.")
        return None

    current_time = datetime.now()


    # ==========================================
    # NETWORK SCAN SECTION
    # ==========================================

    network_section = ""

    if target and scan_results:

        network_section += f"Target: {target}\n\n"

        for port, information in scan_results.items():

            service = information["service"]
            status = information["status"]

            network_section += (
                f"Port {port:<5} "
                f"{service:<8} "
                f"{status}\n"
            )

    else:

        network_section = (
            "No network scan performed.\n"
        )


    # ==========================================
    # FAILED LOGIN SECTION
    # ==========================================

    failed_login_section = ""

    for ip, attempts in sorted(
        results["failed_attempts"].items(),
        key=lambda item: item[1],
        reverse=True
    ):

        if attempts >= 6:
            level = "HIGH"

        elif attempts >= 3:
            level = "MEDIUM"

        else:
            level = "LOW"

        failed_login_section += (
            f"[{level}] "
            f"{ip} - "
            f"{attempts} failed login attempts\n"
        )


    # If there are no failed login attempts
    if not failed_login_section:

        failed_login_section = (
            "No failed login attempts detected.\n"
        )


    # ==========================================
    # BUILD SECURITY REPORT
    # ==========================================

    report = f"""
==================================================
             PYSEC SECURITY REPORT
==================================================

Generated: {current_time.strftime("%d-%m-%Y %H:%M:%S")}


NETWORK SCAN RESULTS
--------------------------------------------------

{network_section}


SECURITY SUMMARY
--------------------------------------------------

Total Events:          {results["total_events"]}
Successful Logins:     {results["successful_logins"]}
Failed Logins:         {results["failed_logins"]}
Invalid User Events:   {results["invalid_users"]}
Suspicious IPs:        {len(results["failed_attempts"])}


FAILED LOGIN ANALYSIS
--------------------------------------------------

{failed_login_section}


THREAT SUMMARY
--------------------------------------------------

Most Suspicious IP:    {results["most_suspicious_ip"]}
Overall Risk Level:    {results["overall_risk"]}


==================================================
             Generated by PySec Automator
==================================================
"""


    # ==========================================
    # SAVE REPORT
    # ==========================================

    try:

        with open(
            "reports/security_report.txt",
            "w"
        ) as report_file:

            report_file.write(report)


    except OSError as error:

        print(
            "\n[ERROR] Could not save "
            "the security report."
        )

        print(f"Details: {error}")

        return None


    # ==========================================
    # SUCCESS MESSAGE
    # ==========================================

    print(
        "Security report generated successfully!"
    )

    print(
        "Location: reports/security_report.txt"
    )

    return report


# ==========================================
# DIRECT TESTING
# ==========================================

if __name__ == "__main__":

    generate_report()